### ISSUE TITLE
npm ci --production doesn't work

### ISSUE THREAD

**Issue by foolip** [GooborgStudios/mdn-bcd-collector#87]
This is because of the ts-node dependency. I'm trying to fix this for https://github.com/foolip/mdn-bcd-collector/pull/2593.

**Comment by queengooborg** [comment]
This is fine because `ts-node` is only used during development and building the collector.  Heroku, my deployer, installs dev dependencies to build the collector, and then removes them once the collector is built.  A part of the build step involves compiling the TypeScript to avoid using ts-node in production (as its memory usage is astonishingly high), so this is alright.
